# Generated by Django 5.0.4 on 2024-12-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_about_options_rename_title_about_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text_on_page', models.TextField(verbose_name='Текст')),
                ('background', models.ImageField(help_text='Фоновое изображение для главной страницы', upload_to='backgrounds/', verbose_name='Фоновое изображение')),
                ('is_active', models.BooleanField(default=False, help_text='Отметьте чтобы стало активным', verbose_name='Активное изображение')),
            ],
            options={
                'verbose_name': 'Фоновое изображение',
                'verbose_name_plural': 'Фоновые изображения',
            },
        ),
    ]
