# Generated by Django 5.0.4 on 2025-01-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_headerbackground_alter_about_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.CharField(verbose_name='Зоголовок текста'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text_on_page',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Зоголовок'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='content',
            field=models.CharField(verbose_name='Зоголовок текста'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='text_on_page',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Зоголовок'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='content',
            field=models.CharField(verbose_name='Зоголовок текста'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='text_on_page',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Зоголовок'),
        ),
    ]
