# Generated by Django 5.0.4 on 2025-01-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_about_content_alter_about_text_on_page_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'контактная информация', 'verbose_name_plural': 'Контактные информации'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=15, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='vk',
            field=models.URLField(blank=True, null=True, verbose_name='Vkontakte'),
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.CharField(verbose_name='Заголовок текста'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='content',
            field=models.CharField(verbose_name='Заголовок текста'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='content',
            field=models.CharField(verbose_name='Заголовок текста'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
